### ISSUE TITLE
Fix warnings: duplicated libraries

### ISSUE THREAD

**Issue by danielfranca** [Bit-Nation/BITNATION-Pangea-react#12]
Log:
```
duplicate manual mock found:
  Module name: ErrorUtils
  Duplicate Mock path: /Users/dfranca/workspace/bitnation/BITNATION-Pangea-react/node_modules/react-native/Libraries/Core/__mocks__/ErrorUtils.js
This warning is caused by two manual mock files with the same file name.
Jest will use the mock file found in:
/Users/dfranca/workspace/bitnation/BITNATION-Pangea-react/node_modules/react-native/Libraries/Core/__mocks__/ErrorUtils.js
 Please delete one of the following two files:
 /Users/dfranca/workspace/bitnation/BITNATION-Pangea-react/node_modules/react-native/node_modules/fbjs/lib/__mocks__/ErrorUtils.js
/Users/dfranca/workspace/bitnation/BITNATION-Pangea-react/node_modules/react-native/Libraries/Core/__mocks__/ErrorUtils.js

```

**Comment by lextiz** [comment]
@danielfranca How can I reproduce this warning? Tried building and running the app and the tests but the warning does not appear.

**Comment by danielfranca** [comment]
@lextiz should be when you run the tests, don't you receive any warning during the tests run?

**Comment by lextiz** [comment]
No warnings after running ```npm install```. Can you reproduce it?

**Comment by danielfranca** [comment]
I can...
Can anyone else reproduce it?

Otherwise might be something on my environment only and then we can close this issue

**Comment by lextiz** [comment]
Which version of npm do you have? Did you try wiping the npm cache and removing node_modules folder?

**Comment by jetpack3331** [comment]
@danielfranca It looks, like you didn't have correct jest config and node_modules isn't in ignored modules for jest

**Comment by jetpack3331** [comment]
I'm without problems, so for me, we can close it

**Comment by florianlenz** [comment]
I am gonna close this issue. If someone experience the problem feel free to reopen it.
