### ISSUE TITLE
Resarch UI/Styles frameworks for React Native

### ISSUE THREAD

**Issue by danielfranca** [Bit-Nation/BITNATION-Pangea-react#13]
ex: Material Design, Bootstrap, Semantic UI

**Comment by Pushplaybang** [comment]
There seem to be limited options, That said, there are a few, I've only toyed with react-native at this stage, so it would great to hear from someone with more experience.

A couple that kept popping up:
* https://react-native-training.github.io/react-native-elements/  - looks fairly comprehensive with generic styles
* https://nativebase.io/ - also seems pretty comprehensive
* https://github.com/xinthink/react-native-material-kit - seems like one of the few that support both Android and iOS
* https://avocode.com/nachos-ui - built with avocode, not sure about this one.

It feels like many of these have limited mileage though, and try to create a unified UI across Android and iOS that both do have quite platform specific paradigms.

As I said, I'm really only starting to look into react native now, but hope this helps get the conversation moving.

**Comment by Pushplaybang** [comment]
@jetpack3331  - any thoughts on these or others?

**Comment by jetpack3331** [comment]
So we can close it, since we're using Nativebase
