### ISSUE TITLE
[panthalassa] build command fails

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/BITNATION-Pangea-react#26]
Hi, since i ejected the project I am getting an error in the "panthalassa_integration" branch during when I run `npm run build`. I am not able to reproduce this error. Maybe someone with more react native experience is able to do so. If you have any question's feel free to ask. 

Edit:
That's the error:
`Module not found: Error: Can't resolve 'invariant' in './BITNATION-Pangea/react\node_modules\react-redux\es\components'`

**Comment by jetpack3331** [comment]
@florianlenz Are you getting this error:
"Module not found: Error: Can't resolve 'invariant' in './BITNATION-Pangea/react\node_modules\react-redux\es\components'"
?

**Comment by florianlenz** [comment]
@jetpack3331 Yes.

**Comment by danielfranca** [comment]
Did you eject in order to add the integration with the Panthalassa?

**Comment by florianlenz** [comment]
@danielfranca Yes.

**Comment by florianlenz** [comment]
Isn't important anymore.
