### ISSUE TITLE
[PROPOSAL] - Git workflow

### ISSUE THREAD

**Issue by Pushplaybang** [Bit-Nation/BITNATION-Pangea-react#28]
## Scope
In order to manage visibility of the stable vs currently in progress code, facilitate collaboration, and protect the production environment, it's often useful to maintain a development branch, (and auto protect the master) so that all PR's are opened against the currently in-progress code on development, and master is always a representation of whats in production. 

## References
* Git workflow comparison: https://www.atlassian.com/git/tutorials/comparing-workflows
* another example - http://nvie.com/posts/a-successful-git-branching-model/

## Proposal
- [x] Define`master` as a production, and protect with status checks and privileged reviewer (in github settings)
- [x] Create `development` branch for current work in progress
- [x] Contributors to open feature or fix branches (ie: `feature/<your-feature-name>` or `fix/<issue-or-bug>`) against development
- [ ] Set target dates using milestones for "next release"
- [ ] Tag release using semantic versioning - see http://semver.org/

## Required
 - [x] Repo Admin to update settings to protect master branch and define `master` merge checks
- [x] Create `development` branch
- [x] Document git workflow for contributors
- [x] Make documenttaion accessible for contributors

## Related 
This is related to #27 

## Expected Outcome
1. Structured workflow to clearly define stable and unstable code
2. Protection for the lastest production build
3. Workflow that supports managing releases and facilitates focus.

**Comment by Pushplaybang** [comment]
@florianlenz  has begun work on defining some of this here
https://docs.google.com/document/d/1wSzNJb--Lbd9RLKnvOZ8P9aK4UKVZ_d_dlYBFeaDxQA/edit

**Comment by Pushplaybang** [comment]
@florianlenz  - has just updated master / dev.  nice one.

**Comment by florianlenz** [comment]
@Pushplaybang @jetpack3331 I pushed to feature/28 Can you checkout the README, read the git workflow and tell me if you are satisfied? @Pushplaybang I think using semantic versioning is currently not important since we don't expose any api's etc.

**Comment by Pushplaybang** [comment]
@florianlenz  - having a look, could you create a pull request, to make review easier?

regarding server, its just a nice sane way to make it very simple to discern major and minor releases, but totally up to you, if you're not keen on it.

**Comment by Pushplaybang** [comment]
@florianlenz  - checked out the readme, looks good.  I'm happy with all of that.

would be nice to add a sought of TL:DR app description at the top, beyond the front for the Pangea jurisdiction, describing the very high-level vision for its functionality, maybe something like: 

> Messaging interface driven app for collaborative smart contracts....

something just to give any new contributors a high-level view of what the end goal is.

**Comment by jetpack3331** [comment]
@florianlenz All is good, except: Branch naming
i think that fix and hotfix branches should be the one

**Comment by florianlenz** [comment]
@jetpack3331 the branching stuff is there: https://docs.google.com/document/d/1wSzNJb--Lbd9RLKnvOZ8P9aK4UKVZ_d_dlYBFeaDxQA/edit

@Pushplaybang True, i also wrote in in my doc (i mean that the repos should contain it). Will add it.

**Comment by Pushplaybang** [comment]
@jetpack3331 @florianlenz sorry I've been so quiet, 

Think that looks good, @florianlenz  - should we maybe get this into a central repo that other repos can link to from their readme's?

@jetpack3331  - fix and hotfix are usually different, as fixes may be during a release sprint, hotfixes are usually opened against master after a release when we've missed something, which is a useful distinction in my opinion, but happy to drop them if you both think they could be confusing.

**Comment by florianlenz** [comment]
@Pushplaybang I planned to just link the google docs document ... I think it's ok. What do you think?

**Comment by jetpack3331** [comment]
It depends on @florianlenz if we leave both branches as one or not

**Comment by florianlenz** [comment]
@jetpack3331 What exactly do you mean?

**Comment by jetpack3331** [comment]
I wrote:
"i think that fix and hotfix branches should be the one"

@Pushplaybang wrote:
" but happy to drop them if you both think they could be confusing."

So i'm asking what do you think about it?

**Comment by florianlenz** [comment]
I would like to keep `fix` and `hotfix`since they address different situations. E.g. I create a `fix/react_native_ios`branch which is just a normal fix for a problem. A typical bug. But if there would be a security problem in the last release i would create a branch from master called `hotfix/encryption` or smth like that. So they address different situations.
