### ISSUE TITLE
Can't run project using docker/expo

### ISSUE THREAD

**Issue by aschwizzy710** [Bit-Nation/BITNATION-Pangea-react#35]
When I try to follow the README instructions to launch the project, I get the following error when running step 5: npm run start:native.

Here is the error: 

npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v6.11.2
npm ERR! Linux 4.9.49-moby
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start:native"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10

npm ERR! missing script: start:native
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /src/app/npm-debug.log

**Comment by jetpack3331** [comment]
There is a bad hint in readme, just run `npm run start-native`

**Comment by jetpack3331** [comment]
@aschwizzy710 Please try develop branch before we will merge develop into master
