### ISSUE TITLE
Native project must be ejected

### ISSUE THREAD

**Issue by jetpack3331** [Bit-Nation/BITNATION-Pangea-react#37]
in future, we will be adding lot of Native code, so we need to upgrade/change dev stack

**Comment by Pushplaybang** [comment]
@jetpack3331  - can we detail what we'd need native modules for, setting up custom build/dev env's will be cool, but could also be time-consuming at this stage, when we're still trying to flesh out the barebones of the app.

**Comment by jetpack3331** [comment]
@Pushplaybang  I did it few days ago and was almost done, so the hard part i have :) And it's needed by @florianlenz for creating own native modules

**Comment by jetpack3331** [comment]
After testing it on ios please close it @florianlenz

**Comment by florianlenz** [comment]
Merged in #38
