### ISSUE TITLE
Follow the mockups

### ISSUE THREAD

**Issue by danielfranca** [Bit-Nation/BITNATION-Pangea-react#6]
![bitnation_pangea_design_03](https://user-images.githubusercontent.com/86538/29417779-a756277c-836a-11e7-8126-e1cf54a9ff56.jpg)

**Comment by Pushplaybang** [comment]
@danielfranca  - Hey There

Is there some way to get involved with the UX & UI design process around these screens and the App?  I'd be really keen to dive in, if there's appetite and interest.

**Comment by xsttx** [comment]
Absolutely! @Pushplaybang are you on the Slack channel?

**Comment by jetpack3331** [comment]
@danielfranca Do you have sources for that images?

**Comment by danielfranca** [comment]
[bitnation_pangea_UIdesign_assetsIos.tar.gz](https://github.com/Bit-Nation/BITNATION-Pangea-react/files/1392333/bitnation_pangea_UIdesign_assetsIos.tar.gz)
Here they go :)

**Comment by Pushplaybang** [comment]
@xsttx  - on slack -do you mean the _dev channel, just joined?  Heading to bed now, but would be keen to join the conversation,

**Comment by jetpack3331** [comment]
Closing and leaving it into history
